### ISSUE TITLE
Regarding the iClone model files (FBX)

### ISSUE THREAD

**Issue by patnaik42** [C3Imaging/SyntheticHeadPose#2]
Hi Shubajit Basak,

I have gone through your paper and appreciate you have done a good work. Few queries.
1) Do you have the generated dataset downloadable from some link?
2) If I want to generate the data using the code given here, I didn't find .FBX files generated from iClone. Can you let me know the path where these files are available, which you used to generate the dataset?

Thank you

**Comment by patnaik42** [comment]
> 

Also I couldn't find instructions to run  in any ReadMe.  Updated ReadMe would be helpful. Thank you.

**Comment by shubhajitbasak** [comment]
We have released the dataset. Please see the readme file for the link.
